#index:
#    path: /
#    controller: App\Controller\DefaultController::index
categories:
  path: /categorie
  defaults:  { _controller: App\Controller\CategorieController::catalogueCategoriesPrincipales }