<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLUUxMUP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLUUxMUP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLUUxMUP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLUUxMUP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLUUxMUP\App_KernelDevDebugContainer([
    'container.build_hash' => 'LUUxMUP',
    'container.build_id' => '0ccb6167',
    'container.build_time' => 1651831318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLUUxMUP');
