<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIiVxNOH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIiVxNOH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIiVxNOH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIiVxNOH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIiVxNOH\App_KernelDevDebugContainer([
    'container.build_hash' => 'IiVxNOH',
    'container.build_id' => '42943c26',
    'container.build_time' => 1651840948,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIiVxNOH');
