<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK1qL2VE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK1qL2VE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK1qL2VE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK1qL2VE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK1qL2VE\App_KernelDevDebugContainer([
    'container.build_hash' => 'K1qL2VE',
    'container.build_id' => '8b1e7a3c',
    'container.build_time' => 1654003419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK1qL2VE');
